service: som-qualtrics-survey-responses
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-west-2
  memorySize: 256

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - secretsmanager:GetSecretValue
      Resource: "arn:aws:secretsmanager:us-west-1:224909451030:secret:som/qualtrics/api_key-hwxXLY"

    - Effect: "Allow"
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - "Ref" : SOMQualtricsSurveyResponseBucket
            - "/*"
  environment:
    BUCKET: ${self:custom.outputBucket}
    QUALTRICS_API_TOKEN: ${self:custom.qualtricsApiToken.SOM_QUALTRICS_API_TOKEN}
    QUALTRICS_DATA_CENTER: "ucsf.co1"

custom:
  outputBucket: 'som-qualtrics-survey-responses-${opt:stage, self:provider.stage}'
  qualtricsApiToken: ${ssm:/aws/reference/secretsmanager/som/qualtrics/api_key~true}

functions:
  storeSurvey1:
    handler: handler.storeSurvey
    events:
      - schedule: rate(4 hours)
    environment:
      SURVEY_ID: SV_exInb81a5EtSLDT
  storeSurvey2:
      handler: handler.storeSurvey
      events:
        - schedule: rate(4 hours)
      environment:
        SURVEY_ID: SV_9yOpJ5At8FaM39H
  storeSurvey3:
      handler: handler.storeSurvey
      events:
        - schedule: rate(4 hours)
      environment:
        SURVEY_ID: SV_bpXobewZ0831pfT
  storeSurvey4:
      handler: handler.storeSurvey
      events:
        - schedule: rate(4 hours)
      environment:
        SURVEY_ID: SV_8CB06g8tnLSSt9P
  storeSurvey5:
      handler: handler.storeSurvey
      events:
        - schedule: rate(4 hours)
      environment:
        SURVEY_ID: SV_bK7vU2Zk1WzBOBf
  storeSurvey6:
      handler: handler.storeSurvey
      events:
        - schedule: rate(4 hours)
      environment:
        SURVEY_ID: SV_d6UsHGihbYWM4sd
  storeSurvey7:
      handler: handler.storeSurvey
      events:
        - schedule: rate(4 hours)
      environment:
        SURVEY_ID: SV_3mlSFVpWmhXC245
  storeSurvey8:
      handler: handler.storeSurvey
      events:
        - schedule: rate(4 hours)
      environment:
        SURVEY_ID: SV_3wqXbUWZxfFQ7bL
  storeSurvey9:
      handler: handler.storeSurvey
      events:
        - schedule: rate(4 hours)
      environment:
        SURVEY_ID: SV_8Bt9BEvMDp8ADWt
  storeSurvey10:
      handler: handler.storeSurvey
      events:
        - schedule: rate(4 hours)
      environment:
        SURVEY_ID: SV_40fxH6k2D56Jmyp
  storeSurvey11:
      handler: handler.storeSurvey
      events:
        - schedule: rate(4 hours)
      environment:
        SURVEY_ID: SV_0jOtXZ54ynJGOMZ
  storeSurvey12:
      handler: handler.storeSurvey
      events:
        - schedule: rate(4 hours)
      environment:
        SURVEY_ID: SV_0SQhsikeG2St445
  storeSurvey13:
      handler: handler.storeSurvey
      events:
        - schedule: rate(4 hours)
      environment:
        SURVEY_ID: SV_4UVvdY2oDgOm6Db
  storeSurvey14:
      handler: handler.storeSurvey
      events:
        - schedule: rate(4 hours)
      environment:
        SURVEY_ID: SV_7WzPjUZlr4YSrPL
  storeSurvey15:
      handler: handler.storeSurvey
      events:
        - schedule: rate(4 hours)
      environment:
        SURVEY_ID: SV_0GrS0vnQVLrbAz3
  storeSurvey16:
      handler: handler.storeSurvey
      events:
        - schedule: rate(4 hours)
      environment:
        SURVEY_ID: SV_aY4PCQzC5slzfHD
  storeSurvey17:
      handler: handler.storeSurvey
      events:
        - schedule: rate(4 hours)
      environment:
        SURVEY_ID: SV_bO6jl8AOueiS0PX
  storeSurvey18:
      handler: handler.storeSurvey
      events:
        - schedule: rate(4 hours)
      environment:
        SURVEY_ID: SV_2498foz7l1fSGlD
  storeSurvey19:
      handler: handler.storeSurvey
      events:
        - schedule: rate(4 hours)
      environment:
        SURVEY_ID: SV_0Ncvxstu2pxlCPb
  storeSurvey20:
      handler: handler.storeSurvey
      events:
        - schedule: rate(4 hours)
      environment:
        SURVEY_ID: SV_9ZDwhVZDlflCXVb
  storeSurvey21:
      handler: handler.storeSurvey
      events:
        - schedule: rate(4 hours)
      environment:
        SURVEY_ID: SV_3OuwCxLQDMIPXgh
  storeSurvey22:
      handler: handler.storeSurvey
      events:
        - schedule: rate(4 hours)
      environment:
        SURVEY_ID: SV_0pvpV6isPLivSvz

# you can add CloudFormation resource templates here
resources:
 Resources:
   SOMQualtricsSurveyResponseBucket:
     Type: AWS::S3::Bucket
     Properties:
       BucketName: ${self:custom.outputBucket}
       PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
       BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
