service: som-qualtrics-survey-responses
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-west-1
  memorySize: 256

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - secretsmanager:GetSecretValue
      Resource: "arn:aws:secretsmanager:us-west-1:224909451030:secret:som/qualtrics/api_key-hwxXLY"

    - Effect: "Allow"
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - "Ref" : SOMQualtricsSurveyResponseBucket
            - "/*"
  environment:
    BUCKET: ${self:custom.outputBucket}
    QUALTRICS_API_TOKEN: ${self:custom.qualtricsApiToken.SOM_QUALTRICS_API_TOKEN}
    QUALTRICS_DATA_CENTER: "ucsf.co1"

custom:
  outputBucket: 'som-qualtrics-survey-responses-${opt:stage, self:provider.stage}'
  qualtricsApiToken: ${ssm:/aws/reference/secretsmanager/som/qualtrics/api_key~true}

functions:
  storeSurvey:
    handler: handler.storeSurvey
    events:
      - schedule: rate(4 hours)
    environment:
      SURVEY_ID: SV_exInb81a5EtSLDT

# you can add CloudFormation resource templates here
resources:
 Resources:
   SOMQualtricsSurveyResponseBucket:
     Type: AWS::S3::Bucket
     Properties:
       BucketName: ${self:custom.outputBucket}
       PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
       BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
